### PR TITLE
Increase verbosity of "Potential_initialise using default init_args" warning

### LINKED ISSUE #490: print fewer warnings
Is this warning really necessary every time `WARNING: Potential_initialise using default init_args "Potential xml_label=GAP_CsPbBr3_pert_and_froz_phon_gap_rss_universal_SOAP.freq_weighted_10_max_wt_1e7"
`

### PR DESCRIPTION
**Pull request by bernstei**
Add message_type and verbosity optional arguments to print_warning.  Use these argument to only print `'Potential_initialise using default init_args'` for VERBOSE and up

closes #490

### CODE REVIEW

**Comment by bernstei** [comment]
Looks like there needs to be a coordinated change to `GAP`, unless I leave `print_warnings` for backward compatibility. Which should I do @jameskermode ?

**Comment by jameskermode** [comment]
Hmm, ok, yes, let’s leave a backwards compatible print_warning() wrapper for now.

**Comment by bernstei** [comment]
OK - wrapper exists, let's see if tests pass. Also, I made the other place that extends the cutoff be silent iff the initial cutoff is the default -1 (as opposed to a real and too-small value).

**Comment by jameskermode** [comment]
Looks good, thank you! I'll do a new PyPI wheel release after merging since this is now fully automated and painless.

**Pull request merged**
