### PR TITLE
make public explicit in system_module

### PR DESCRIPTION
**Pull request by alinelena**

### CODE REVIEW

**Comment by bernstei** [comment]
I found a couple more things that were not listed as `public` in the modified `system_module`.  Is Travis going to automatically catch more of these?  I know I don't have every possible feature active in Makefile.inc.

I can't seem to push, so they are: `is_file_readable`, `alloc_trace`, `dealloc_trace`

**Comment by alinelena** [comment]
Hi @noambernstein yes there are quite few which are not public... at the moment I try to list all that will make travis happy but as you say some will be missed for sure.

**Comment by alinelena** [comment]
@noambernstein  strange you cannot add commits i ticked the option too.

**Comment by bernstei** [comment]
I think it's an ssh:// vs. https:// thing, but there were so few changes I didn't bother fixing it.

**Comment by alinelena** [comment]
@noambernstein ok.. though i did something silly since i usually use gitlab.

**Comment by bernstei** [comment]
I think it's fine now.  Should we merge?

**Comment by jameskermode** [comment]
Yes, let's do it. Thank you @alinelena and sorry for the long delay.

**Pull request merged**
