### PR TITLE
bin: Upate shebangs to use env

### PR DESCRIPTION
**Pull request by HaoZeke**
Fixes obscure errors in HPC environments.

### CODE REVIEW

**Comment by gabor1** [comment]
Is it going to cause problems elsewhere.. ? Anybody else have an opinion ?

**Comment by noambernstein** [comment]
On Tue, Aug 25, 2020 at 5:30 AM gabor1 <notifications@github.com> wrote:

>
>
> What is the rationale for this change?
>
>
Presumably some HPC where bash isn’t in /bin?

**Comment by jameskermode** [comment]
Currently it's breaking the CI so can't be merged like this

**Comment by gabor1** [comment]
The CI is breaking because it always breaks for forks: the secret is not available. The change is simple enough that I’m happy to merge it if people agree it is unlikely to break things. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by bernstei** [comment]
> On Aug 25, 2020, at 6:52 AM, James Kermode <notifications@github.com> wrote:
> Currently it's breaking the CI so can't be merged like this
> 
Weird - do you understand why?  I've been using that syntax for finding python3 for ages.

**Comment by gabor1** [comment]
well, I'll merge it and then it will pass (I think)

**Comment by bernstei** [comment]
> On Aug 25, 2020, at 8:30 AM, gabor1 <notifications@github.com> wrote:
> 
> well, I'll merge it and then it will pass (I think)

Is this statement really true?  If so, doesn't that defeats the purpose of CI tests?

**Comment by gabor1** [comment]
what you are really saying is, we should figure out how to get around this secret business. I have no idea :-)

**Comment by gabor1** [comment]
(the CI tests still have a purpose they will tell us AFTER the merge whether it works or not, and if it doesn't then we can do something about it - but I agree, pre-testing the merge requests would be nice)

**Pull request merged**
