### PR TITLE
Change pip3 to pip in quippy/Makefile to fix compilation

### PR DESCRIPTION
**Pull request by eszter137**
Quippy didn't compile with the pip3 version.

### CODE REVIEW

**Comment by eszter137** [comment]
In the end, this might be unnecessary because linking `pip` as `pip3` can also solve the problem. (It might be also necessary to deactivate and activate the environment to make `pip3 show` work for some reason.)

**Comment by eszter137** [comment]
It seems the new miniconda environments don't always have the `pip3` command so changing the `pip3` to `pip` would work without any linking in the environment.

**Comment by gabor1** [comment]
We could test for the presence of pip3, and if it doesn’t exist, then use pip. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment]
Should we also just test for the version of python > 2 and fail gracefully if it isn’t true??

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by eszter137** [comment]
I've found a way to check for the python version:
```
PY_VERSION=$(shell python -c "import sys;t='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(t)");
ifeq (${PY_VERSION:0:1},2)
```
 Where would it be sensible to include the stop? Is it fine under install in quippy/Makefile? (and with the error message: `"Error: python3 needed."`?)

**Comment by gabor1** [comment]
surely not under install, but the very first thing when "make quippy" is run? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by eszter137** [comment]
ok, thank you.
and if we know that the python in the PATH is python3, could we just go ahead using `pip`?

**Comment by bernstei** [comment]
I don't know how universal the output format is, but "pip --version" also returns information we could confirm is consistent with python's version:
[bernstei@vpn214062 ~]$ pip --version
pip 20.0.2 from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
I think to be maximally robust we have to accommodate both pip and pip3 as possible executable names. There's a standard for python (https://www.python.org/dev/peps/pep-0394/ <https://www.python.org/dev/peps/pep-0394/>), but apparently not for pip (or people are ignoring it).

								Noam

**Comment by eszter137** [comment]
The python version check is in the `Makefile` but the pip version is not yet checked.
(The Makefile also contains the deletion of the `*.s` files when doing `make deepclean`.)

**Comment by eszter137** [comment]
Another problem is that one might have only pip in the conda environment and have an earlier version of pip3 outside the environment that would be found by `command -v pip3` or `which pip3` so maybe it's not enough to check for the existence of the command but we'd need to test the version as Noam suggested.
```
(py3) es732@es732lap:~$ command -v pip3
/usr/bin/pip3
(py3) es732@es732lap:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
(py3) es732@es732lap:~$ command -v pip
/home/es732/miniconda3/envs/py3/bin/pip
(py3) es732@es732lap:~$ pip --version
pip 20.0.2 from /home/es732/miniconda3/envs/py3/lib/python3.8/site-packages/pip (python 3.8)
```
Do we need a new version of `pip3` or is it fine to use an older one?

(Also, when installing the f90wrap, the installation guide suggests using pip (`pip install src/f90wrap`) which is not consistent with using pip in the quippy installation.)

**Comment by gabor1** [comment]
I don't think the Makefile can sort out the giant pile of turd that python environments have become. Let's offer environment variables PIP and PYTHON to allow the user to specify which programs are used, this solves all of these issues.

**Comment by gabor1** [comment]
It’s best to put into the `make config` as a question, showing the full path of the default, and record the answer in Makefile.inc. this will remind the users to check. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by eszter137** [comment]
Did you mean something like this?

**Comment by jameskermode** [comment]
Looks like a good approach to me

**Comment by gabor1** [comment]
I think for the default you should call pip not pip3.

**Comment by eszter137** [comment]
Thank you. Ok, I'll change it to `pip`.

**Comment by eszter137** [comment]
I added a test in line 64 to print the output of ${PIP} show f90wrap:
https://github.com/eszter137/QUIP/blob/public/quippy/Makefile#L64
but the problem in the Travis build might also be that it used a different pip (maybe pip3) to install the f90wrap.

**Pull request merged**
