### PR TITLE
WIP: Replace tabs with spaces

### PR DESCRIPTION
**Pull request by Sideboard**
Replaces tabs with spaces (usually eight).

:exclamation:  To avert future tabs, [code scanning](https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors) and/or [Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) could be employed.

### CODE REVIEW

**Comment by stenczelt** [comment]
Huge thumbs up for this change

**Comment by Sideboard** [comment]
I have changed the tabs in other files as well, leaving out mostly Makefiles and patch files. Scrutiny should be spent on scripts with string comparison where they tabs are included in whitespace search (and replace?). I have rebased onto the current public.

**Comment by Sideboard** [comment]
I have left the first three commits separate to ease checking a bit. Can be squashed if you like.

**Comment by Sideboard** [comment]
The Github diff view has a bug. It shows tabsizes at the start of the line with two less spaces than it should. I did not find a simple solution for that.

**Review by jameskermode — APPROVED** [review]
I've checked the diff and am happy for this to be merged. Thanks!

**Pull request merged**
