### PR TITLE
LAMMPS interface change (NOT backwards compatible!)

### PR DESCRIPTION
**Pull request by max-veit**
Changed the quip/lammps interface (the mechanism by which lammps can call quip potentials) so that quip also gets the persistent atom IDs.  This change is obviously not backwards compatible, so introduced another function lammps can call to determine the API version to make future changes easier - or at least less jarring for the end user.  The version number QUIP returns is an integer that should be manually incremented if (and only if!) the interface is changed in an incompatible way.

I propose that these changes only be merged once the next version of lammps releases, so we don't force our users to grab the git version of lammps.

### CODE REVIEW

**Comment by gabor1** [comment]
can you keep tabs on when the lammps release is made ? 

-- Gábor

**Comment by tdaff** [comment]
Assuming that different versions do not compile together, then the daily Travis build will helpfully break when the next stable version of lammps is tagged.

**Comment by max-veit** [comment]
Should be appearing soon on the [lammps github page](https://github.com/lammps/lammps/releases)

**Comment by tdaff** [comment]
Is this in stable lammps now? Seems to be breaking docker so you can probably merge!

**Pull request merged**
