### PR TITLE
Refactor/matrix pointers

### PR DESCRIPTION
**Pull request by Sideboard**
Make matrix components pointers for optional memory savings. Default to allocatable-like behaviour, including `final` procedure.

### CODE REVIEW

**Comment by jameskermode** [comment]
QUIP CI fixed in #384 - if you merge that into this branch you can check nothing new breaks

**Comment by Sideboard** [comment]
Probably best to rebase onto the merged #384 before merging this PR.

**Comment by jameskermode** [comment]
Yup - I've now merged #384 so rebasing on `public` would be sensible.

**Comment by albapa** [comment]
Great! My only question is about copy, that uses the allocate code path, is there a value in shallow copying?

**Pull request merged**
