### PR TITLE
Fix LBFGS compilation with Intel compilers

### LINKED ISSUE #334: Problem building LAMMPs with the QUIP package
Hi!

I’m trying to compile LAMMPs with the QUIP package using the Intel compilers.
However, the compilation fails when trying to link the CXX executable lmp with the error:
`ld: liblammps.so.0: undefined reference to 'lb2_'`

I’m using a libquip.a also build with the intel compilers using thelinux_x86_64_ifort_icc makefile.
Something worth noting is that compiling LAMMPs without QUIP using the Intel compilers works and compiling LAMMPs with QUIP but using the gcc compilers also works.
I have tracked down the error to the fact that LAMMPs is compiled with shared libs, this seems to cause a problem when including the QUIP package.
But since everting works fine using the gcc compilers is suspect that the error comes from the compilation of libquip.a
Are the any compiler flags that I need to modify in the Makefile.linux_x86_64_ifort_icc file in order to create a libquip.a that can be used to build LAMMPS with QUIP and shared libs using the Intel compilers?

I attaced the logfile with the error
[easybuild-LAMMPS-29Oct2020-20210823.153124.ChdBQ.log](https://github.com/libAtoms/QUIP/files/7036428/easybuild-LAMMPS-29Oct2020-20210823.153124.ChdBQ.log)

/Daniel

### PR DESCRIPTION
**Pull request by RemiLacroix-IDRIS**
Fixes #334.

### CODE REVIEW

**Comment by jameskermode** [comment]
Thank you! We don't have working Intel tests in CI unfortunately (WIP in #405).

@Sideboard would you be willing to test this change locally with Intel before we merge?

**Comment by Sideboard** [comment]
Can do.

**Comment by RemiLacroix-IDRIS** [comment]
Just realized that if:
https://github.com/libAtoms/QUIP/blob/5ce3d41475e53ba459285338ae353bb124a68416/Makefile.config#L142
refers to this specific issue, I should probably change the message.

Let me know if you can confirm it works.

**Comment by Sideboard** [comment]
@RemiLacroix-IDRIS How do you include QUIP in LAMMPS? What options are you using?

**Comment by RemiLacroix-IDRIS** [comment]
I let LAMMPS grab and compile QUIP: https://github.com/lammps/lammps/blob/develop/cmake/Modules/Packages/ML-QUIP.cmake.

**Comment by Sideboard** [comment]
I could reproduce the compile step error and the PR does solve it. Have not verified whether the program runs correctly.

**Comment by jameskermode** [comment]
thanks @Sideboard for testing and @RemiLacroix-IDRIS  for the fix.

**Comment by RemiLacroix-IDRIS** [comment]
You're welcome! :)

**Pull request merged**
