### PR TITLE
added RS core-softened potential

### PR DESCRIPTION
**Pull request by albapa**

### CODE REVIEW

**Comment by jameskermode** [comment]
Looks good from a quick scan. Since you asked for a review, how about a test, though? e.g. could add a new class below the [Lennard-Jones](https://github.com/libAtoms/QUIP/blob/public/tests/test_pot.py#L156) test in `tests/test_pot.py`.

**Comment by albapa** [comment]
I thought the whole idea of using PRs rather than pushing straight to main was to ask for reviews :)
Good point, I've added the test - I hope this is roughly what you meant.

**Comment by jameskermode** [comment]
Thanks - although that new test is a bit degenerate in that it just checks that `get_potential_energy()` gives the same answer as `calculate()`. This was added since we had a bug there before, but it was at a higher level than the LJ potential.  Probably comparing to a fixed reference energy would be a better bet here.

**Comment by albapa** [comment]
OK, I get it now!

**Comment by jameskermode** [comment]
LGTM

**Review by jameskermode — APPROVED** [review]

**Pull request merged**
