### PR TITLE
449 build system issue gap+turgogap install

### PR DESCRIPTION
**Pull request by albapa**

### CODE REVIEW

**Comment by Sideboard** [comment]
~~Last references to HAVE_TURBOGAP:~~

- ~~build/linux_x86_64_gfortran_openmpi+openmp/Makefile.inc~~
- ~~build/linux_x86_64_ifort_icc_avon_intelmpi/Makefile.inc~~
- ~~build/linux_x86_64_gfortran/Makefile.inc~~

**Comment by albapa** [comment]
These are created locally after `make config`.

**Comment by Sideboard** [comment]
Sorry, you are absolutely right. I thought it was the `arch/*`.

**Comment by stenczelt** [comment]
good stuff! thanks!

**Pull request merged**
