### PR TITLE
fixing PGI & nvidia  fortran compiler errors

### PR DESCRIPTION
**Pull request by alvarovm**

### CODE REVIEW

**Comment by jameskermode** [comment]
thanks @alvarovm - is this now ready to go? I've triggered the CI. Will there be a corresponding PR for GAP as well?

**Comment by alvarovm** [comment]
I have not tested this with GAP yet, I am doing this now.

**Comment by alvarovm** [comment]
@jameskermode  I tested this when HAVE_GAP=1 is present, it should work now.

**Comment by jameskermode** [comment]
Rerunning the CI, let's see if it passes now.

Are there any changes needed within the GAP repo itself? If so you need to make a PR against https://github.com/libAtoms/GAP and also updatedthe git submodule "pointer" as part of this PR.

**Comment by alvarovm** [comment]
ok, it seems that GAP compile with nvfortran out of the box.

**Review by jameskermode — APPROVED** [review]

**Comment by jameskermode** [comment]
Great - in that case since the CI is now passing and everything looks fine in the diff then I'm happy to merge. Many thanks for the contribution!

**Comment by alvarovm** [comment]
Good! and you welcome.

**Pull request merged**
