### PR TITLE
use mpi module as default, add preprocessor _OLDMPI to keep old behav…

### LINKED ISSUE #220: gfortran10 and mpi failure to compile
gfortran 10 seems to be very picky with mpi.

```
 1118 |   call MPI_Bcast(v, size(v), MPI_DOUBLE_PRECISION, my_root, this%communicator, err)
      |                 1
......
 1245 |        v, len(v(1,1))*size(v), MPI_CHARACTER, &
      |       2          
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/CHARACTER(*)).
/home/drFaustroll/codes/gabor/QUIP/src/libAtoms/MPI_context.f95:1087:17:

```

and similar.

attached a patch dealing with the problem in a dirty and quick way.

full solution is to replace 
#include "mpif.h" 
with
use mpi

[0001-keep-gfortran-10-happy.patch.zip](https://github.com/libAtoms/QUIP/files/4915348/0001-keep-gfortran-10-happy.patch.zip)

### PR DESCRIPTION
**Pull request by alinelena**
…iour, fixes #220

### CODE REVIEW

**Comment by gabor1** [comment]
I'll wait for Travis to run, but our default tests don't run MPI I think... maybe they should? In the meantime someone should test this with MPI turned on. maybe @stenczelt since you are compiling with MPI anyway on your summer project ?

**Comment by alinelena** [comment]
ok travis will not run seems due to missing token... is this cause I am doing a pr from a fork?

**Comment by stenczelt** [comment]
Well, I am able to compile with MPI. I was wondering if you can give me a little more info of what the current changes are inteded @alinelena. What is the OLDMPI and MPI business?

**Comment by bernstei** [comment]
Basically
inlcude 'mpif.h'
vs.
use mpi

i.e. interface via old fashioned include file vs. more modern F90 module file.  I guess gfortran 10 has problems with mpif.h, but for many years we avoided the module because it led to unnecessary dependencies between precise compiler version used to compile MPI and the fortran code.

**Comment by alinelena** [comment]
from what I gathered gfortran-10  when comes to routines without interfaces is quite unhappy if you have two calls or more to the same routine, in the same unit that differ by type of arguments.
Best example is MPI_Bcast, if you bcast an integer and then some real in the same unit, it will complain about mismatching arguments.  (there is no interface if you include mpif.h)

there are two solutions to this problem
1. to provide interfaces, simplest way is to use modules. 
2. use some compiler flag -fallow-argument-mismatch to turn error into warning... 

obviously I prefer 1. if you look through the changes, you can see the advantage of using the module, in System.F95 around line 2085 you will see caught a valid bug in the usage of mpi_initialized.

**Comment by stenczelt** [comment]
well, from what I know of Fortran so far (senior people please correct me if I am wrong) not having an interface in that case is bad practice indeed...

Nonetheless, `use mpi` should be understoos by any compiler, even the ancient ones some can have on old ubuntu distros, so if you eliminate the related bugs that were not cought due to `mpif.h` then this should compile everywhere I guess.

**Comment by noambernstein** [comment]
The problem isn’t ancient compilers not supporting modules. It is inherent
to FORTRAN 90 that modules exist. The problem used to be that any compiler
version change broke module compatibility, so every tiny point release
change would require recompiling mpi, and if you try to support multiple
compiler and/or mpi versions this gets to be a pain.

That said, the point is that current compilers don’t break compatibility so
often anymore, so counting on modules is reasonable.

**Comment by gabor1** [comment]
Now that the travis has been fixed to deal with pull requests correctly (skipping the GAP build), can you rebase this pull request to the head and try it again? let's see if travis eats it this time.

**Comment by alinelena** [comment]
> Now that the travis has been fixed to deal with pull requests correctly (skipping the GAP build), can you rebase this pull request to the head and try it again? let's see if travis eats it this time.

all green it seems!

**Pull request merged**
