### PR TITLE
Allow for 6-vectors when reading xyz files

### PR DESCRIPTION
**Pull request by bernstei**
Allow either 3- or 6-vectors when reading xyz files.  9 is still automatically cast to 3x3 matrix.

### CODE REVIEW

**Comment by jameskermode** [comment]
@gabor1 @bernstei shall we merge this together with https://github.com/libAtoms/GAP/pull/7

**Comment by bernstei** [comment]
On Oct 23, 2020, at 10:12 AM, James Kermode <notifications@github.com<mailto:notifications@github.com>> wrote:

@gabor1<https://github.com/gabor1> @bernstei<https://github.com/bernstei> shall we merge this together with libAtoms/GAP#7<https://github.com/libAtoms/GAP/pull/7>

I'm ready for it.  How are we with unit testing QUIP?  I'd like to have a test for virial vs. stress fitting, just to ensure I didn't break anything.  I could put together a tiny database and ga_fit command line, and we could compare final GAP xml files.

**Comment by jameskermode** [comment]
I think a unit test would be a good idea. We can run tests which depend on GAP, and they do run in Travis.

**Comment by jameskermode** [comment]
Maybe best to add the test to this PR, then merge the GAP changes, then merge this once its all OK?

**Comment by bernstei** [comment]
> On Oct 23, 2020, at 11:09 AM, James Kermode <notifications@github.com> wrote:
> Maybe best to add the test to this PR, then merge the GAP changes, then merge this once its all OK?
> 

So you mean testing the QUIP change first, since they're more straightforward, and then the GAP, in both 6-vector and special 3x3 forms?  What's the current form of the CI tests?

**Comment by jameskermode** [comment]
OK, good idea. If you add a new file named `tests/test_xyz.py` or similar it should be picked up automatically.

**Comment by bernstei** [comment]
> OK, good idea. If you add a new file named `tests/test_xyz.py` or similar it should be picked up automatically.

I think I need an actual Fortran test.  I did it using `convert` and running it from a shell script.

**Comment by bernstei** [comment]
We should contemplate a more serious change, say allowing the Fortran extxyz to read arbitrary vectors, and special case only specific names (stress, virial, lattice) to 3x3 matrices.

**Comment by bernstei** [comment]
I just updated the test to check the value of the 6-vector, but if that passes, I'm happy to merge.

**Comment by stenczelt** [comment]
@bernstei @jameskermode what is the status of this one? Are we waiting on something?

**Comment by jameskermode** [comment]
It won't be merged, as all XYZ I/O will be outsourced to https://github.com/libAtoms/extxyz which is nearly ready

**Comment by stenczelt** [comment]
Sure, let's close it then! I am awaiting the release of that.

**Comment by bernstei** [comment]
We have several people running into issues with the workflow because ASE and gap disagree on 6 vs. 9 element stress.  Can. we revive this and merge it?  Or should I just update this branch and tell them to use it instead?

**Comment by bernstei** [comment]
@jameskermode What do you think about merging this one after all?  It's only changes to extxyz.c (and a test), so it's small, and anyway it'll be replaced when we put in the new reader.   Getting it into public will make things like the workflow that use the pypi version work without having to wait for the final extxyz reader/writer.

**Comment by jameskermode** [comment]
Fine with me, although note that PyPI version doesn’t automatically update so we’d have to do a new release.

**Comment by jameskermode** [comment]
Also I’m not sure the shell script based tests are actually running in the CI. could you check that before merging?

**Comment by bernstei** [comment]
How do I check the tests in the CI?

**Comment by jameskermode** [comment]
Look at the log output linked in the PR page e.g. https://github.com/libAtoms/QUIP/pull/233/checks?check_run_id=3161950140

There used to be a Python test which ran the shell scripts but not sure if it’s active. I’m on holiday this week so am only looking on my phone which requires a lot of scrolling…

**Comment by bernstei** [comment]
No problem - I'll check.  Is there another way to do tests these days, if that shell-based test isn't really active?  Or should I just try to revive the python calling shell test?

**Comment by jameskermode** [comment]
Probably just revive the Python calling.

**Comment by bernstei** [comment]
How do I deal with the path issue?  Can I count on newly compiled fortran executables being in `tests/../build/${QUIP_ARCH}` (and also on `$QUIP_ARCH` being defined)`?  I guess it needs to work both in CI and manually from the QUIP directory (above tests).

**Comment by jameskermode** [comment]
> Can I count on newly compiled fortran executables being in tests/../build/${QUIP_ARCH} (and also on $QUIP_ARCH being defined)`?

Yes to both in CI. Here's how it's built:

https://github.com/libAtoms/QUIP/blob/public/.github/workflows/Build.yml#L34

and then tests are invoked as `make test`, also with `QUIP_ARCH` set

https://github.com/libAtoms/QUIP/blob/public/.github/workflows/Build.yml#L50

If easier then `make test` could directly call the shell scripts rather than going in and out of Python.

**Comment by bernstei** [comment]
I added `tests/test_shell_scripts.py`, and the tests are apparently passing, but there's not enough info printed for me to confirm that that test is actually running.

**Comment by jameskermode** [comment]
I think adding a `-v` to the end of the Python test script invocation should give one output line per test, which would be an improvement overall.

**Comment by bernstei** [comment]
I'm happy to do that, if you can guide me to where that invocation happens.

**Comment by jameskermode** [comment]
https://github.com/libAtoms/QUIP/blob/public/tests/Makefile#L31

seems to be already one `-v` there, not sure if `-vv` would do what we want.

**Comment by bernstei** [comment]
I tried -vv.  Out of curiosity, is there a reason we used unittest rather than the ubiquitous pytest?

**Comment by jameskermode** [comment]
No, just inertia. Would be good to change to pytest at some point.

**Comment by bernstei** [comment]
Definitely _not_ running the shellscript test, but maybe I need to do something else - I'm used to pytest.  I'll look at it soon.

**Comment by bernstei** [comment]
Looks to me like it finally passes (and also applies the quip test).  Do we want to try to revive the other shell-based tests, or just merge?

**Comment by jameskermode** [comment]
Thanks, I’m fine with merging now and coming back to the other tests later. I’ll open an issue suggesting doing that and switching to pytest

**Comment by jameskermode** [comment]
Is there a corresponding change that needs to be made to GAP? The old PR libAtoms/GAP#7 mentioned above must have been in the old private GAP repo

**Comment by bernstei** [comment]
The history is lost, but I believe that change was in fact merged https://github.com/libAtoms/GAP/blob/3c67cdfd20ae8100e37d1980f9335e33b08fa893/gap_fit_module.f95#L660

**Pull request merged**
